const int NUMBER_OF_ELEMENTS = 509;
const int MAX_SIZE = 140;

char birdFacts [NUMBER_OF_ELEMENTS] [MAX_SIZE] = {
{"There are over 11,000 known species of birds in the world"}, 
{"The Ostrich is the largest bird and cannot fly, but it is an excellent runner"}, 
{"Hummingbirds are the only birds that can fly backward"}, 
{"Penguins are birds but are unable to fly"}, 
{" They are exceptional swimmers"}, 
{"The Arctic Tern has the longest migratory journey, covering about 18,641 miles (30,000 km) annually"}, 
{"The smallest bird in the world is the Bee Hummingbird, weighing around 1"}, 
{"6 to 2 grams"}, 
{"Falcons are among the fastest birds, reaching speeds of up to 240 mph (386 km/h) in a dive"}, 
{"The Lyrebird is known for its incredible ability to mimic natural and artificial sounds"}, 
{"The Kakapo, a nocturnal parrot from New Zealand, is the heaviest parrot and is critically endangered"}, 
{"Crows are highly intelligent birds and can solve complex problems"}, 
{"Birds are descendants of dinosaurs"}, 
{"The kiwi bird is native to New Zealand and is the only bird with nostrils at the tip of its beak"}, 
{"Albatrosses have the longest wingspan of any living bird, reaching up to 9 ft 10in feet (3 meters)"}, 
{"The African Grey Parrot is known for its exceptional ability to mimic human speech"}, 
{"Some birds, like the Common Swift, can spend almost their entire lives in the air"}, 
{"The Hoatzin chick has claws on its wings, a feature retained from its dinosaur ancestors"}, 
{"The Mute Swan is not entirely mute; it can make grunting and hissing sounds"}, 
{"The Harpy Eagle is one of the largest and most powerful eagles in the world"}, 
{"The Australian Lyrebird is an expert mimic and can imitate chainsaws and camera shutters"}, 
{"The Greater Roadrunner is known for catching and eating rattlesnakes"}, 
{"The Shoebill has a massive shoe-shaped bill and is native to tropical swamps in central tropical Africa"}, 
{"The Kakapo is the only flightless parrot and is critically endangered"}, 
{"The Atlantic Puffin can hold multiple fish in its beak at once"}, 
{"The Andean Condor has one of the longest lifespans of any bird, reaching up to 70 years"}, 
{"Owls have specialized feathers that enable silent flight"}, 
{"The Helmeted Hornbill has solid casques on its bill, making it one of the heaviest birds in the world"}, 
{"The Superb Lyrebird has one of the most complex and beautiful song repertoires"}, 
{"The Kakapo, or night parrot, is primarily nocturnal and is herbivorous"}, 
{"The Kaka, a parrot from New Zealand, is known for its playful behavior"}, 
{"The Eurasian Wren has one of the loudest songs relative to its size"}, 
{"The Northern Mockingbird can mimic the songs of other birds and even mechanical sounds"}, 
{"The Secretary Bird is known for its ability to stomp on prey with its powerful legs"}, 
{"The California Condor has the largest wingspan of any North American bird"}, 
{"The Oilbird is the only nocturnal flying fruit-eating bird"}, 
{"The Atlantic Puffin's beak changes color during the breeding season"}, 
{"The Laysan Albatross is one of the longest-lived birds, with individuals reaching over 60 years"}, 
{"The Bald Eagle is the national bird and symbol of the United States"}, 
{"The Victoria Crowned Pigeon is one of the largest pigeon species"}, 
{"The Common Raven is highly intelligent and can solve complex problems"}, 
{"The Blue-footed Booby gets its name from its distinctive blue feet"}, 
{"The Dodo, native to Mauritius, is an extinct flightless bird"}, 
{"The Emperor Penguin is the tallest and heaviest penguin species"}, 
{"The Barn Owl has a heart-shaped facial disc"}, 
{"The Pink-headed Warbler is a rare and colorful bird found in Central America"}, 
{"The Rüppell's Vulture is the highest-flying bird, having been spotted at over 37,000 feet"}, 
{"The Eurasian Nuthatch can walk headfirst down tree trunks"}, 
{"The European Robin is not closely related to American robins"}, 
{"The Australian Lyrebird can imitate the calls of other bird species"}, 
{"The Northern Saw-whet Owl has a distinctive, repetitive tooting call"}, 
{"The Bowerbird builds elaborate structures to attract mates"}, 
{"The Potoo, native to Central and South America, has excellent camouflage"}, 
{"The Eurasian Eagle-Owl has large, striking orange eyes"}, 
{"The Gouldian Finch is also known as the Rainbow Finch due to its vibrant colors"}, 
{"The Red-crowned Crane is considered a symbol of longevity in East Asia"}, 
{"The Wilson's Bird-of-Paradise is one of the smallest birds of paradise"}, 
{"The Andean Cock-of-the-Rock has bright orange plumage and a unique courtship display"}, 
{"The Yellow-eyed Penguin is one of the rarest penguin species and is native to New Zealand"}, 
{"The Eurasian Spoonbill has a distinctive spoon-shaped bill used for feeding in shallow water"}, 
{"The Eurasian Jay is known for its habit of caching food for later consumption"}, 
{"The Painted Bunting is often described as the most beautiful bird in North America"}, 
{"The African Crowned Eagle is a powerful raptor known for its impressive hunting skills"}, 
{"The Wilson's Storm-Petrel spends most of its life at sea and only comes to land to breed"}, 
{"The Horned Puffin gets its name from the fleshy 'horns' above its eyes during the breeding season"}, 
{"The Marabou Stork has one of the largest wingspans among storks"}, 
{"The Black-crowned Night Heron is known for its nocturnal feeding habits"}, 
{"The Anna's Hummingbird can survive sub-freezing temperatures by entering a state of torpor"}, 
{"The Montezuma Oropendola builds long, hanging nests with multiple chambers"}, 
{"The Western Bluebird is known for its bright blue plumage and melodious song"}, 
{"The Eurasian Tree Sparrow is not closely related to the House Sparrow"}, 
{"The Andean Hillstar is a high-altitude hummingbird found in the Andes Mountains"}, 
{"The Northern Gannet is an expert diver and can plunge into the water from great heights"}, 
{"The European Roller is known for its striking blue and orange plumage"}, 
{"The Kea, native to New Zealand, is the world's only alpine parrot"}, 
{"The Wandering Albatross has the longest wingspan of any living bird species"}, 
{"The Western Tanager is known for its bright yellow and black plumage"}, 
{"The Hoopoe has a distinctive crown of feathers on its head and is found in Eurasia and Africa"}, 
{"The Tufted Puffin has bright orange bill plates and tufts of feathers on its head"}, 
{"The Crested Auklet has unique plumes on its head that resemble a punk rock hairstyle"}, 
{"The Andean Motmot has a distinctive racket-shaped tail and inhabits cloud forests"}, 
{"The Philippine Eagle is one of the largest and most powerful eagles in the world"}, 
{"The Eurasian Curlew has one of the longest bills among shorebirds"}, 
{"The Horned Guan is a rare and elusive bird found in the cloud forests of Central America"}, 
{"The Saddle-billed Stork has a colorful, saddle-shaped bill and is found in Africa"}, 
{"The Long-tailed Tit builds elaborate nests using spider silk for added strength"}, 
{"The Northern Lapwing is known for its acrobatic display flights"}, 
{"The Red-winged Blackbird is recognized by the bright red patches on its wings"}, 
{"The Blue Tit is a small, colorful bird known for its agility and playful behavior"}, 
{"The Resplendent Quetzal is considered a symbol of freedom and wealth in Central America"}, 
{"The Superb Fairywren has a complex social structure with cooperative breeding"}, 
{"The Eurasian Magpie is highly intelligent and has been observed using tools"}, 
{"The Green Honeycreeper has vibrant green and blue plumage and is found in Central and South America"}, 
{"The Harlequin Duck is known for its striking black, white, and blue plumage"}, 
{"The Australian Brush-turkey builds large nests made of leaves and other vegetation"}, 
{"The Eurasian Bullfinch has a distinctive call and feeds on buds, fruits, and seeds"}, 
{"The Eurasian Coot has large, lobed feet adapted for swimming"}, 
{"The African Grey Hornbill seals itself in a tree cavity during the breeding season, leaving only a small slit for food exchange"}, 
{"The Eurasian Skylark is known for its melodious, continuous song during its display flight"}, 
{"The Violet Sabrewing is a large hummingbird with stunning violet and green plumage"}, 
{"The Aldabra Drongo is known for its mimicry, imitating the calls of other bird species"}, 
{"The Black-capped Chickadee is known for its distinctive 'chick-a-dee-dee-dee' call"}, 
{"The Victoria's Riflebird is known for its elaborate courtship display involving iridescent plumage"}, 
{"The Andean Ibis has a distinctive long, curved bill and is found in South America"}, 
{"The Northern Jacana has exceptionally long toes that help it walk on floating vegetation"}, 
{"The Magellanic Penguin is named after the explorer Ferdinand Magellan"}, 
{"The Indian Roller is known for its aerial acrobatics during courtship displays"}, 
{"The Scarlet Macaw is one of the most colorful parrots, with vibrant red, blue, and yellow plumage"}, 
{"The Eurasian Spoonbill is known for its unique spoon-shaped bill, used to sweep through shallow water to find food"}, 
{"The Snowy Owl is well-adapted to cold environments, and its feathers provide excellent insulation"}, 
{"The Yellow-crowned Night Heron is named for the distinctive yellow feathers on its head"}, 
{"The Northern Shoveler has a large spatula-shaped bill, which it uses to filter food from the water"}, 
{"The Southern Cassowary is a large flightless bird known for its striking blue and black coloration"}, 
{"The Green-cheeked Conure is a small parrot with vibrant green plumage and a playful personality"}, 
{"The Eurasian Bullfinch has a unique feeding technique, using its bill to strip buds from branches"}, 
{"The Toco Toucan has the largest bill of any toucan species, making up about one-third of its body length"}, 
{"The Blue-crowned Motmot has a distinctive racket-shaped tail and is found in Central and South America"}, 
{"The Spectacled Eider is a sea duck named for the distinctive rings around its eyes"}, 
{"The Tufted Duck is known for its tuft of feathers at the back of its head and its striking black and white plumage"}, 
{"The Andean Flamingo is one of the rarest flamingo species and is found in the high-altitude Andean plateaus"}, 
{"The Brown-throated Sunbird is a small, colorful bird found in Southeast Asia"}, 
{"The Northern Pygmy Owl is a tiny owl with a surprisingly fierce demeanor"}, 
{"The European Goldfinch is known for its red face and black and gold wings"}, 
{"The Philippine Hanging Parrot has a unique ability to sleep upside down"}, 
{"The Sooty Tern has one of the longest migratory journeys, covering thousands of miles across the ocean"}, 
{"The Wilson's Warbler is a small songbird with bright yellow plumage and a black cap"}, 
{"The Yellow Warbler is known for its vibrant yellow plumage and sweet, musical song"}, 
{"The White-cheeked Turaco has striking green and white plumage and is found in central Africa"}, 
{"The Eurasian Skylark is known for its ascending song, often performed while hovering in the air"}, 
{"The Eurasian Oystercatcher has a long, orange bill and is known for its distinctive 'piping' call"}, 
{"The Yellow-throated Warbler is a small bird with a yellow throat and a distinctive black mask"}, 
{"The Resplendent Quetzal was considered sacred by the ancient Maya and Aztec civilizations"}, 
{"The Andean Hillstar is a high-altitude hummingbird found in the Andes Mountains"}, 
{"The Yellow-eyed Junco is known for its bright yellow eyes and distinct plumage variations"}, 
{"The Palm Cockatoo is known for its drumming behavior, using sticks and hollow trees to create rhythmic sounds"}, 
{"The Saffron Finch is a bright yellow bird with a distinctively curved bill, native to South America"}, 
{"The Masked Lapwing is known for its loud, piercing call and distinctive facial markings"}, 
{"The Sword-billed Hummingbird has a bill longer than its body, adapted for feeding on long-tubed flowers"}, 
{"The Chestnut-mandibled Toucan is one of the larger toucan species, with a colorful bill"}, 
{"The Long-tailed Manakin is known for its elaborate courtship displays, involving coordinated dancing"}, 
{"The Splendid Fairywren has striking blue and black plumage and lives in social groups"}, 
{"The Red-capped Robin has a vibrant red cap on its head and is found in Australia"}, 
{"The Crested Guan is a large bird with a distinctive crest of feathers on its head"}, 
{"The Magnificent Frigatebird has a distinctive red throat pouch, which inflates during courtship displays"}, 
{"The White-cheeked Gibbon is a primate known for its distinctive calls, often heard in the treetops"}, 
{"The Gouldian Finch is also known as the Rainbow Finch due to its vibrant plumage"}, 
{"The Pileated Woodpecker is one of the largest woodpecker species in North America"}, 
{"The Orange-bellied Parrot is one of the rarest parrot species, native to Australia"}, 
{"The Eurasian Blackcap has a melodious song and is known for its warbling call"}, 
{"The Magnificent Hummingbird has iridescent green and blue plumage and is found in Central America"}, 
{"The Northern Carmine Bee-eater is known for its vibrant carmine-red plumage"}, 
{"The Black-throated Blue Warbler has distinctive black and blue plumage"}, 
{"The Steller's Sea Eagle is one of the largest and heaviest eagles in the world"}, 
{"The Common Merganser is known for its striking black and white plumage and long, slender bill"}, 
{"The Madagascar Fish Eagle is one of the rarest eagles, native to Madagascar"}, 
{"The Helmeted Manakin is known for its acrobatic courtship displays, involving rapid wing movements"}, 
{"The Black-crowned Sparrow-lark has cryptic plumage, providing excellent camouflage in its habitat"}, 
{"The Horned Sungem is a hummingbird with a distinctive long, straight bill and iridescent plumage"}, 
{"The Harlequin Macaw is a hybrid parrot resulting from the crossbreeding of a Blue-and-gold Macaw and a Green-winged Macaw"}, 
{"The Oriental Dwarf Kingfisher is one of the smallest and most colorful kingfisher species"}, 
{"The Eurasian Griffon Vulture is known for its soaring flight and scavenging habits"}, 
{"The Blyth's Tragopan is a pheasant species with striking plumage and fleshy facial wattles"}, 
{"The Black-capped Chickadee can remember the locations of thousands of individual seeds it has hidden"}, 
{"The Blue Jay is known for its intelligence and mimicry of other bird species"}, 
{"The Eurasian Reed Warbler is a migratory bird that travels long distances between breeding and wintering grounds"}, 
{"The Southern Carmine Bee-eater is known for its spectacular aerial displays during courtship"}, 
{"The Bearded Vulture has a unique diet, primarily consisting of bones"}, 
{"The Swallow-tailed Kite is an elegant raptor known for its distinctive forked tail"}, 
{"The Long-tailed Widowbird has an exceptionally long tail, which can be more than half a meter in length"}, 
{"The Wattled Jacana has long, fleshy wattles on its face and is known for walking on floating vegetation"}, 
{"The Eurasian Nutcracker has a strong bill adapted for opening pine cones and extracting seeds"}, 
{"The Tufted Puffin has vibrant orange bills and tufts of feathers during the breeding season"}, 
{"The Himalayan Monal is one of the most colorful pheasant species, native to the Himalayas"}, 
{"The Bar-tailed Godwit has one of the longest non-stop migratory flights, covering over 7,000 miles"}, 
{"The Common Yellowthroat is known for its distinctive 'witchety-witchety-witch' song"}, 
{"The Wilson's Phalarope is one of the few bird species where the females are more brightly colored than the males"}, 
{"The Snowy-crowned Robin-Chat has a distinctive white crown and is found in sub-Saharan Africa"}, 
{"The White-throated Sparrow has a song that sounds like 'Oh sweet Canada Canada'"}, 
{"The Raggiana Bird-of-Paradise is known for its elaborate courtship displays in Papua New Guinea"}, 
{"The Blue-winged Kookaburra is a large kingfisher with a striking blue and white plumage"}, 
{"The Pied Kingfisher hovers over the water before diving to catch its prey"}, 
{"The Eurasian Blue Tit is a small bird with bright blue and yellow plumage"}, 
{"The Red-legged Seriema is a ground-dwelling bird found in South America with strong legs adapted for running"}, 
{"The African Fish Eagle is known for its distinctive call, often described as a 'haunting scream'"}, 
{"The Crested Owl has distinctive 'ear tufts' that are not actually ears"}, 
{"The Philippine Serpent Eagle is a raptor found in the Philippines and is known for hunting snakes"}, 
{"The Lilac-breasted Roller is known for its stunning plumage and aerial acrobatics"}, 
{"The Cape Barren Goose has striking black and white plumage and is native to Australia"}, 
{"The Great Blue Turaco has vibrant green and blue plumage and is found in central Africa"}, 
{"The Northern Fulmar is a seabird known for its ability to excrete a foul-smelling stomach oil as a defense mechanism"}, 
{"The Black-throated Magpie-Jay is a vocal and social bird found in Central America"}, 
{"The Red-faced Cormorant has bright red facial skin during the breeding season"}, 
{"The White-tailed Tropicbird has a long, white tail streamer and is found in tropical oceans"}, 
{"The White-eared Hummingbird is a small hummingbird with a distinctive white patch behind its eye"}, 
{"The Eurasian Green Woodpecker has a distinctive laughing call"}, 
{"The Eastern Whip-poor-will is known for its repetitive 'whip-poor-will' call during the breeding season"}, 
{"The Long-tailed Duck has one of the longest diving depths among ducks"}, 
{"The Guianan Cock-of-the-Rock has bright orange plumage and is known for its lekking displays"}, 
{"The Eurasian Cuckoo is a brood parasite, laying its eggs in the nests of other bird species"}, 
{"The Rosy-faced Lovebird is a small parrot with a bright pink face"}, 
{"The African Grey Hornbill has a long, down-curved bill and is found in sub-Saharan Africa"}, 
{"The White-rumped Shama has a melodious and varied song"}, 
{"The Southern Ground Hornbill is known for its distinctive red facial and throat skin"}, 
{"The Gila Woodpecker is adapted to desert life and nests in saguaro cacti"}, 
{"The Oriental Pratincole is a migratory bird that breeds in Asia and winters in Australia"}, 
{"The Northern Jacana has exceptionally long toes that allow it to walk on floating vegetation"}, 
{"The Amazon Kingfisher is a large kingfisher species found in the Americas"}, 
{"The Grey-headed Kingfisher has striking gray and orange plumage and is found in Africa"}, 
{"The Pied Crow is highly adaptable and can be found in a variety of habitats in Africa"}, 
{"The Great Grey Owl is the largest owl by length but not by weight"}, 
{"The Collared Aracari is a toucan species known for its distinctive black and white collar"}, 
{"The Red-billed Quelea is considered the most abundant wild bird species in the world"}, 
{"The Madagascar Bee-eater has striking plumage and is native to Madagascar and nearby islands"}, 
{"The Grey Crowned Crane is known for its elaborate courtship dances"}, 
{"The Elegant Trogon is a colorful bird found in tropical and subtropical forests"}, 
{"The Australian Pelican has the longest bill of any bird, measuring up to 18 inches (46 cm)"}, 
{"The Eurasian Hobby is a small falcon known for its swift and agile flight"}, 
{"The Superb Starling has glossy, iridescent plumage and is found in East Africa"}, 
{"The Red Knot is known for its long-distance migratory journeys, covering thousands of miles"}, 
{"The Eastern Yellow Robin is a small bird found in Australia with a striking yellow belly"}, 
{"The Palmchat is the national bird of the Dominican Republic and is known for its communal nesting habits"}, 
{"The Galah is a pink and grey cockatoo found in Australia and is known for its playful behavior"}, 
{"The Purple Finch's plumage can vary from raspberry red to a more subdued brown"}, 
{"The African Grey Parrot is one of the most intelligent bird species and is a popular pet"}, 
{"The Greater Painted-Snipe has a unique feeding behavior, probing for prey with its long bill"}, 
{"The Blue-gray Tanager is a colorful bird found in Central and South America"}, 
{"The Wood Stork has a distinctive bald head and is found in wetlands in the Americas"}, 
{"The Eurasian Sparrowhawk is known for its agility and swift flight through dense vegetation"}, 
{"The Verreaux's Eagle is a large bird of prey found in sub-Saharan Africa"}, 
{"The Eurasian Wigeon is a dabbling duck with a distinctive whistling call"}, 
{"The Pink Robin is a small, colorful bird found in Australia with a pink breast"}, 
{"The Eurasian Golden Oriole has striking yellow and black plumage"}, 
{"The Chestnut-crowned Antpitta is known for its distinctive song and secretive behavior"}, 
{"The Brown-headed Cowbird is a brood parasite that lays its eggs in the nests of other bird species"}, 
{"The Red-crowned Crane is one of the rarest cranes and is considered a symbol of luck in Japan"}, 
{"The Indian Roller is also known as the 'Blue Jay' and is found in South Asia"}, 
{"The Black Guillemot has distinctive black and white plumage and bright red legs"}, 
{"The Northern Raven is known for its intelligence and problem-solving abilities"}, 
{"The Collared Owlet is a small owl with a distinctive white 'collar' on its nape"}, 
{"The Red-necked Phalarope has reversed sexual roles, with females being more brightly colored"}, 
{"The Sanderling is a small shorebird known for its quick, running movements on sandy beaches"}, 
{"The Common Stonechat is named for its habit of perching on stones and other elevated spots"}, 
{"The Secretarybird is a large bird of prey found in sub-Saharan Africa"}, 
{"The Blue-crowned Hanging Parrot has a vibrant blue crown and is found in Southeast Asia"}, 
{"The White-headed Woodpecker is known for its preference for feeding on pine seeds"}, 
{"The White-rumped Snowfinch is a hardy bird found in high-altitude mountainous regions"}, 
{"The Australian Pratincole is a shorebird that breeds in Australia and migrates to Southeast Asia"}, 
{"The Black-winged Kite is known for its hovering flight while hunting for prey"}, 
{"The Red-vented Bulbul has a distinctive red patch on its lower belly"}, 
{"The Great Potoo is a nocturnal bird known for its excellent camouflage during the day"}, 
{"The Marbled Teal is a dabbling duck with intricate marbled patterns on its plumage"}, 
{"The Masked Booby has a distinctive black mask around its eyes and is found in tropical oceans"}, 
{"The Northern Harrier is known for its low, coursing flight over open fields"}, 
{"The White-necked Jacobin is a large hummingbird with striking white and iridescent blue plumage"}, 
{"The Laughing Dove has a distinctive soft, cooing call"}, 
{"The White-faced Whistling Duck is known for its whistling calls and distinctive facial markings"}, 
{"The Orange-headed Thrush is a songbird with striking orange and black plumage"}, 
{"The Red-billed Firefinch has bright red plumage and is found in sub-Saharan Africa"}, 
{"The Long-tailed Jaeger is a seabird known for its agile flight and long, pointed tail"}, 
{"The Chestnut-mandibled Toucan has a large, colorful bill and is found in Central and South America"}, 
{"The Blue-winged Teal is a dabbling duck with striking blue wing patches"}, 
{"The Eurasian Greenfinch has a distinctive, twittering song and is found in Europe, Asia, and North Africa"}, 
{"The Red-faced Warbler has vibrant red plumage on its face and is found in North America"}, 
{"The White-cheeked Tern is known for its elegant flight and plunging dives for fish"}, 
{"The Pin-tailed Sandgrouse is a bird found in arid regions and is known for its long, pointed tail feathers"}, 
{"The Golden-headed Cisticola is a small bird with a distinctive golden crown and is found in Africa"}, 
{"The Western Bluebird has bright blue plumage and is found in North America"}, 
{"The Long-tailed Duck has a distinct, long tail and is found in northern regions around the world"}, 
{"The Orange-bellied Parrot is one of the rarest parrot species, native to Australia"}, 
{"The Red-legged Partridge is a game bird with distinctive red legs and is native to parts of Europe"}, 
{"The Wilson's Snipe is known for its winnowing display during the breeding season"}, 
{"The Arctic Tern has the longest migratory journey, traveling from the Arctic to Antarctica"}, 
{"The Common Raven is known for its intelligence and complex vocalizations"}, 
{"The Cattle Egret is often found foraging near cattle, feeding on insects disturbed by their movement"}, 
{"The Black-throated Diver is a diving bird with a striking black throat and white plumage"}, 
{"The Greater Ani is a bird known for its communal nesting habits and distinctive calls"}, 
{"The Eurasian Crag Martin is a swift with a distinctive white rump and is found in rocky areas"}, 
{"The Spot-billed Toucanet is a small toucan with a distinctive spotted bill"}, 
{"The Eurasian Siskin has vibrant yellow plumage with black streaks and is found in Europe and Asia"}, 
{"The Blue-crowned Conure is a parrot with striking blue and green plumage and is native to South America"}, 
{"The Red-billed Blue Magpie is known for its long tail and vibrant blue and red plumage"}, 
{"The European Nightjar is a nocturnal bird with cryptic plumage, blending into its surroundings"}, 
{"The Olive-backed Sunbird is a small bird with iridescent green and yellow plumage"}, 
{"The Common Whitethroat is a warbler with a distinctive white throat and is found in Europe and Asia"}, 
{"The Broad-billed Tody is a colorful bird with a broad bill and is found in the Caribbean"}, 
{"The White-throated Dipper is a bird that bobs up and down while standing on rocks in fast-flowing streams"}, 
{"The Striped Manakin is known for its courtship displays involving rapid wing movements"}, 
{"The African Darter is a water bird with a long, slender neck and is found in sub-Saharan Africa"}, 
{"The Red-tailed Black Cockatoo has a distinctive red tail and is native to Australia"}, 
{"The Eurasian Bullfinch has a striking black cap and is found in Europe and Asia"}, 
{"The White-crowned Sparrow has distinctive black and white head stripes"}, 
{"The Variable Sunbird is a small bird with colorful plumage found in sub-Saharan Africa"}, 
{"The Eurasian Treecreeper is a small bird that climbs tree trunks in search of insects"}, 
{"The Black-throated Magpie-Jay is known for its loud calls and vibrant blue and white plumage"}, 
{"The White-winged Snowfinch is a bird adapted to alpine environments with white plumage"}, 
{"The Rose-ringed Parakeet is a parrot species with a distinctive rose-colored ring around its neck"}, 
{"The Southern Ground Hornbill is known for its loud calls and is native to sub-Saharan Africa"}, 
{"The Yellow-throated Leaflove is a bird found in Africa with yellow plumage and a melodious song"}, 
{"The Slaty-backed Gull is a large gull with distinctive slate-gray plumage on its back"}, 
{"The Eurasian Blackcap has a melodic song and is known for its warbling calls"}, 
{"The Tawny Frogmouth is a nocturnal bird with cryptic plumage resembling tree bark"}, 
{"The Blue-throated Toucanet has a striking blue throat and is found in Central and South America"}, 
{"The Pacific Golden Plover is a migratory bird that travels long distances between its breeding and wintering grounds"}, 
{"The Buff-breasted Sandpiper is a shorebird with a buff-colored breast and is found in the Americas"}, 
{"The American Avocet has a distinctive upturned bill and is known for its elegant wading behavior"}, 
{"The Arctic Jaeger is a seabird known for its aggressive behavior and kleptoparasitic tendencies"}, 
{"The Black-and-white Warbler is a small bird with bold black-and-white streaks on its plumage"}, 
{"The Crested Barbet is a bird with a distinctive spiky crest and is found in sub-Saharan Africa"}, 
{"The Green Heron is known for its ability to use bait to attract fish, dropping insects or other objects into the water to lure prey"}, 
{"The Violet-crowned Hummingbird is a striking hummingbird with vibrant violet and green plumage"}, 
{"The Sandhill Crane is known for its elaborate courtship dances, involving synchronized jumps and calls"}, 
{"The Common Myna is a highly adaptable bird with a remarkable ability to mimic human speech and other sounds"}, 
{"The Crested Guineafowl is a large bird with a distinctive, helmet-like crest on its head"}, 
{"The Tufted Titmouse is a small songbird known for its bold and curious behavior"}, 
{"The Collared Kingfisher is a bird of prey known for its striking blue and white plumage"}, 
{"The Red-legged Honeycreeper is a small bird with bright blue and red plumage found in the Americas"}, 
{"The Eastern Yellow Wagtail is a migratory bird known for its yellow plumage and wagging tail"}, 
{"The Eurasian Bullfinch has a unique diet, feeding primarily on buds and young shoots"}, 
{"The Palm Warbler is a small songbird known for its habit of pumping its tail while foraging on the ground"}, 
{"The Steller's Jay is a colorful corvid with striking blue and black plumage found in western North America"}, 
{"The Great Cormorant is a diving bird known for its ability to swim underwater in search of prey"}, 
{"The White-faced Ibis is a wading bird with a distinctive white face and long, curved bill"}, 
{"The Yellow-headed Blackbird is known for its vibrant yellow head and loud, varied songs"}, 
{"The Eastern Towhee is a bird with striking black and rufous plumage and a distinctive 'drink-your-tea' call"}, 
{"The Masked Lapwing is a bird with a distinctive black and white facial mask and a loud, screeching call"}, 
{"The Grey Wagtail is a bird known for its distinctive undulating flight and yellow underparts"}, 
{"The Plain Chachalaca is a large bird with a loud and raucous vocalization found in the Americas"}, 
{"The White-browed Coucal is a large, ground-dwelling bird with striking white markings on its face"}, 
{"The Common Chiffchaff is a small migratory bird known for its distinctive 'chiff-chaff' call"}, 
{"The Eurasian Spoonbill is a wading bird with a distinctive spoon-shaped bill used for feeding"}, 
{"The African Wood Owl is a nocturnal bird known for its haunting calls in sub-Saharan Africa"}, 
{"The Red-capped Plover is a shorebird with a striking red cap on its head and is found in Australia"}, 
{"The White-faced Whistling Duck is a bird with a distinctive white face and a whistling call"}, 
{"The Eurasian Blackbird is a songbird known for its melodic song and widespread distribution"}, 
{"The Eurasian Cuckoo is a brood parasite that lays its eggs in the nests of other bird species"}, 
{"The Mountain Bluebird is a thrush with striking blue plumage found in North America"}, 
{"The Eurasian Woodcock is a wading bird known for its cryptic plumage and aerial courtship displays"}, 
{"The European Pied Flycatcher is a migratory bird known for its black and white plumage"}, 
{"The Orange-breasted Sunbird is a small bird with vibrant orange and green plumage found in southern Africa"}, 
{"The Northern Waterthrush is a migratory songbird known for its habit of foraging in and around water"}, 
{"The Puna Ibis is a high-altitude bird with distinctive white plumage and a long, red bill"}, 
{"The Glossy Ibis is a wading bird with iridescent plumage and a distinctive long, curved bill"}, 
{"The Eurasian Bullfinch has a melodious song and is known for feeding on fruit buds"}, 
{"The Green-cheeked Amazon is a parrot with vibrant green plumage and a playful personality"}, 
{"The African Pygmy Kingfisher is a small, colorful bird with striking blue and orange plumage"}, 
{"The Eurasian Black Vulture is a large bird of prey known for its soaring flight"}, 
{"The Malachite Sunbird is a striking bird with vibrant green and blue plumage found in southern Africa"}, 
{"The Buff-throated Saltator is a songbird with a distinctive buff-colored throat"}, 
{"The White-winged Tern is a migratory bird known for its striking black and white plumage"}, 
{"The Grasshopper Warbler is a small bird with a distinctive reeling song"}, 
{"The Orange-fronted Parakeet is a parrot with a bright orange forehead found in New Zealand"}, 
{"The Northern Bobwhite is a ground-dwelling bird known for its whistled 'bob-white' call"}, 
{"The Red-legged Seriema is a large bird with long legs and is known for its loud calls"}, 
{"The Great Tit is a small bird with striking black, white, and yellow plumage"}, 
{"The Hooded Oriole is a colorful bird with striking black and orange plumage found in the Americas"}, 
{"The Eurasian Oystercatcher is a bird with a distinctive long, orange bill and a loud 'piping' call"}, 
{"The Common Tern is a migratory bird with a graceful flight and distinctive black cap"}, 
{"The Violet-backed Starling is a bird with iridescent violet and black plumage found in Africa"}, 
{"The Black-bellied Whistling Duck is a duck species with a distinctive whistling call and black belly"}, 
{"The White-throated Kingfisher is known for its striking blue and white plumage and a loud, cackling call"}, 
{"The Eurasian Tree Sparrow is a small bird with a chestnut crown and is found in Europe and Asia"}, 
{"The Yellow-billed Hornbill is a bird with a long, down-curved bill and is native to sub-Saharan Africa"}, 
{"The Red-crowned Crane is one of the rarest cranes and is considered a symbol of longevity in Japan"}, 
{"The Australian White Ibis is a wading bird with a long, curved bill and is found in Australia"}, 
{"The Olive-sided Flycatcher is a bird with a distinctive 'quick-three-beers' song and is found in North America"}, 
{"The Glossy Swiftlet is a small, swift-flying bird with glossy black plumage found in Southeast Asia"}, 
{"The Oriental Magpie-Robin is a songbird with bold black and white markings and a melodious song"}, 
{"The African Skimmer is a bird with a unique feeding technique, skimming its lower mandible through water to catch fish"}, 
{"The Black-collared Starling is known for its striking black plumage with a contrasting white collar"}, 
{"The Sand Martin is a small swallow species that nests in burrows dug into sandbanks"}, 
{"The Toco Toucan has one of the largest bills relative to body size among all birds"}, 
{"The Eurasian Jay is known for its habit of caching food for future consumption"}, 
{"The Common Eider is a sea duck known for its soft down feathers, which are used to line its nest"}, 
{"The Yellow-bellied Sapsucker is a woodpecker species known for drilling holes in trees to feed on sap"}, 
{"The Western Osprey is a raptor specialized in catching fish and is found near bodies of water"}, 
{"The Blue-headed Vireo is a migratory songbird with a blue-gray head and distinctive facial markings"}, 
{"The Long-billed Curlew has an exceptionally long bill, used to probe in mud for invertebrates"}, 
{"The Northern Flicker is a woodpecker with a unique color pattern and a distinctive, loud call"}, 
{"The White-crowned Hornbill is a bird with a large, downward-curved bill and a white crown"}, 
{"The Northern Pintail is a dabbling duck with a long, pointed tail and elegant plumage"}, 
{"The Cape Gannet is a seabird with striking black eye markings and is native to southern Africa"}, 
{"The Eurasian Penduline Tit is known for its unique nest, resembling a hanging sack made of plant fibers"}, 
{"The Azure-winged Magpie is a bird with vibrant blue and black plumage and is native to East Asia"}, 
{"The Olive Warbler is a small songbird with olive-green plumage and is found in North America"}, 
{"The Yellow-throated Vireo is a migratory bird with a bright yellow throat and a melodious song"}, 
{"The Laysan Albatross is known for its remarkable ability to cover vast distances during long-distance flights"}, 
{"The Dark-eyed Junco is a sparrow species with distinct plumage variations based on geographic location"}, 
{"The Chestnut-collared Longspur is a songbird with a chestnut-colored collar and is found in North America"}, 
{"The Black-crowned Tchagra is a bird found in Africa with striking black and white plumage"}, 
{"The Northern Hawk Owl is a diurnal owl species known for its keen hunting abilities during daylight"}, 
{"The European Greenfinch is a songbird with vibrant green plumage and is found in Europe and Asia"}, 
{"The Straw-headed Bulbul is known for its melodious song and is native to Southeast Asia"}, 
{"The Fork-tailed Flycatcher is a bird with a distinctive forked tail and is found in the Americas"}, 
{"The Red-fronted Macaw is a parrot species with bright red plumage and is native to South America"}, 
{"The White-tailed Tropicbird has long tail streamers and is found in tropical oceans"}, 
{"The White-cheeked Barbet is a bird with a vibrant green body and distinctive white cheeks"}, 
{"The Red-winged Pigeon is known for its bright red patches on the wings and is found in Africa"}, 
{"The Little Tern is a small seabird with a distinctive black cap and is found worldwide"}, 
{"The Green Iora is a small bird with striking green and black plumage and is found in Southeast Asia"}, 
{"The Swainson's Thrush is a migratory songbird known for its flute-like song"}, 
{"The Marbled Godwit is a shorebird with a long, upturned bill and is found in the Americas"}, 
{"The Red-throated Diver is a diving bird with a distinctive red throat and is found in northern regions"}, 
{"The African Firefinch is a small bird with bright red plumage and is native to sub-Saharan Africa"}, 
{"The Broad-tailed Hummingbird is a migratory hummingbird with a distinctive buzzing sound during flight"}, 
{"The European Roller is known for its striking blue and orange plumage and is found in Europe and Asia"}, 
{"The Wilson's Warbler is a small songbird with bright yellow plumage and a black cap"}, 
{"The Yellow-crowned Bishop is a weaver bird with a bright yellow crown and is found in Africa"}, 
{"The Blue-faced Parrotfinch is a small finch with a vibrant blue face and is native to Australia"}, 
{"The Spectacled Owl is a nocturnal bird with striking facial markings that resemble spectacles"}, 
{"The Yellow-tufted Honeyeater is a bird with distinctive yellow tufts of feathers on its head, native to Australia"}, 
{"The Greater Yellowlegs is a shorebird with long, bright yellow legs and a distinctive call"}, 
{"The Common Nighthawk is a nocturnal bird known for its erratic flight and insect-catching abilities"}, 
{"The Blue-throated Hummingbird is a large hummingbird with vibrant blue throat feathers"}, 
{"The Indian Roller is the state bird of four Indian states and is known for its aerial acrobatics"}, 
{"The Eurasian Spoonbill has a unique feeding technique, sweeping its bill from side to side in shallow water"}, 
{"The Black-chinned Sparrow is a songbird with a black throat patch and is found in North America"}, 
{"The Slender-billed Gull is a gull species with a slender, slightly upturned bill"}, 
{"The White-cheeked Turaco is a bird with vibrant green and white plumage, native to Africa"}, 
{"The Fork-tailed Drongo is a songbird with a distinctive forked tail and is found in Africa and Asia"}, 
{"The Sooty Shearwater is a seabird known for its long-distance migratory flights across the world's oceans"}, 
{"The Blue-winged Teal is a dabbling duck with striking blue wing patches and a distinctive call"}, 
{"The Chestnut-backed Chickadee is a small songbird with a chestnut-colored back, found in North America"}, 
{"The White-rumped Sandpiper is a shorebird with a distinctive white rump and is found in the Americas"}, 
{"The Elegant Crested Tinamou is a ground-dwelling bird with a distinctive crest on its head, native to South America"}, 
{"The Brown-headed Nuthatch is a small bird that often forages headfirst down tree trunks"}, 
{"The Red-winged Blackbird is a songbird with striking red and yellow shoulder patches"}, 
{"The Green Woodhoopoe is a bird with vibrant green and black plumage and is native to Africa"}, 
{"The Eurasian Reed Warbler is a migratory bird that breeds in Europe and winters in Africa"}, 
{"The Yellow-breasted Chat is a songbird with a bright yellow breast and a variety of complex vocalizations"}, 
{"The White-crowned Sparrow has a distinct white crown and is known for its clear, whistle-like song"}, 
{"The White-throated Needletail is a swift with distinctive white markings on its throat"}, 
{"The Rüppell's Vulture is a large vulture with a pale head and is native to sub-Saharan Africa"}, 
{"The Australian Shelduck is a large duck species with striking black and white plumage"}, 
{"The Common Hoopoe is a bird known for its distinctive 'crown' of feathers and is found in Europe, Asia, and Africa"}, 
{"The Purple Sunbird is a small bird with vibrant purple and iridescent plumage, native to South Asia"}, 
{"The Black-winged Stilt is a wading bird with long, thin legs and a distinctive black-and-white color pattern"}, 
{"The Common Redpoll is a small finch with a red crown and is found in northern regions"}, 
{"The Piping Plover is a small shorebird with a distinctive piping call and is found in North America"}, 
{"The European Shag is a seabird with dark plumage and a distinctive crest on its head"}, 
{"The Orange Bishop is a weaver bird with bright orange plumage and is native to Africa"}, 
{"The Plain-colored Tanager is a small bird with plain plumage, native to Central and South America"}, 
{"The Yellow-rumped Warbler is a migratory songbird with distinctive yellow patches on its rump"}, 
{"The White-eyed Vireo is a songbird with bright white eyes and a cheerful, melodious song"}, 
{"The Common Murre is a seabird with a distinctive black and white color pattern and is found in the Northern Hemisphere"}, 
{"The White-throated Toucan is a large-billed toucan with a striking black and white color pattern"}, 
{"The Eurasian Curlew is a large wading bird with a long, down-curved bill"}, 
{"The Greater Honeyguide is a bird known for its unique relationship with honey badgers, guiding them to beehives"}, 
{"The Blue Grosbeak is a songbird with striking blue and brown plumage, found in North and Central America"}, 
{"The White-winged Crossbill is a finch with a unique crossed bill adaptation for extracting seeds from conifer cones"}, 
{"The Whiskered Tern is a migratory bird with long, slender black whiskers and is found globally"}, 
{"The Black-crowned Waxbill is a small finch with a distinctive black crown and is native to Africa"}, 
{"The American Woodcock is a ground-dwelling bird known for its elaborate courtship displays"}, 
{"The Crested Francolin is a bird with a distinctive crest on its head and is found in Africa"}, 
{"The Ring-necked Pheasant is a game bird with colorful plumage and a distinctive white neck ring"}, 
{"The Yellow-fronted Canary is a small songbird with bright yellow plumage, native to Africa"}, 
{"The Eastern Whipbird is a bird with a distinctive 'whip' call and is found in Australia"}, 
{"The Great Antshrike is a bird with striking black and white plumage, native to South America"}, 
{"The Black Skimmer is a bird with a unique bill, longer on the lower mandible, used for skimming the water surface"}, 
{"The Eurasian Nuthatch is a small bird known for its habit of climbing down tree trunks headfirst"}, 
{"The Yellow-throated Sparrow is a songbird with a bright yellow throat and is found in Asia"}, 
{"The Long-tailed Cormorant is a bird with a long, slender tail and is native to Africa"}, 
{"The Eurasian Linnet is a small finch with a distinctive crimson forehead and breast"}, 
{"The Eurasian Hobby is a small falcon known for its swift, acrobatic flight"}, 
{"The Brown Pelican is a seabird known for its unique hunting behavior, diving from the air to catch fish"}, 
{"The White-winged Chough is a bird with black plumage and distinctive white wing patches"}, 
{"The Chestnut-breasted Coronet is a hummingbird with vibrant chestnut-colored plumage"}, 
{"The Sedge Warbler is a migratory songbird with a distinctive, melodious song"}, 
{"The Spot-billed Duck is a dabbling duck with a distinctive yellow patch on its bill"}, 
{"The Western Kingbird is a flycatcher with a white throat and distinctive yellow belly"}, 
{"The Pacific Swallow is a bird with long, pointed wings and a deeply forked tail"}, 
{"The Red-throated Pipit is a small bird with a red throat and is found in Europe and Asia"}, 
{"The White-headed Buffalo Weaver is a weaver bird with a distinctive white head"}, 
{"The Eurasian Bullfinch has a melodious song and is known for its colorful plumage"}, 
{"The White-rumped Shama is a songbird with a melodious and varied song, native to Southeast Asia"}, 
{"The Black-collared Thrush is a bird with striking black and white plumage"}, 
{"The Tricolored Heron is a wading bird with distinctive blue-gray, white, and rust-colored plumage"}, 
{"The Eurasian Golden Oriole is known for its striking yellow and black plumage"}, 
{"The African Grey Hornbill is a bird with a large, downward-curved bill and is native to Africa"}, 
{"The Yellow-faced Grassquit is a small finch with yellow facial markings, found in the Americas"}, 
{"The Sooty Falcon is a bird of prey with dark plumage and is found in the Middle East"}, 
{"The Little Green Bee-eater is a colorful bird with green plumage and a long, slender bill"}, 
{"The Eurasian Oystercatcher is a wading bird with a distinctive long, orange bill"}, 
{"The Brown-throated Wattle-eye is a small bird with a distinctive wattled eye marking"}, 
{"The Stilt Sandpiper is a shorebird with long, thin legs and is found in the Americas"}, 
{"The Spectacled Eider is a sea duck with a distinctive white eye patch"}, 
{"The Green-winged Pytilia is a finch with striking green and black plumage, found in Africa"}, 
{"The Bar-tailed Godwit is a migratory bird with a long bill and is known for its long-distance flights"}, 
{"The White-vented Myna is a bird with a distinctive white patch on its rump"}, 
{"The Eastern Whip-poor-will is a nocturnal bird known for its repetitive 'whip-poor-will' call"}, 
{"The European Stonechat is a bird named for its habit of perching on stones and other elevated spots"}, 
{"The Pied Wagtail is a bird with black and white plumage and a distinctive wagging tail"}, 
{"The Eastern Meadowlark is a songbird with bright yellow underparts and a melodic song"}, 
{"The Red-shouldered Vanga is a bird with striking red and black plumage, native to Madagascar"}, 
{"The European Goldfinch is a small finch with vibrant red, black, and yellow plumage"}, 
{"The Sulphur-crested Cockatoo is a large cockatoo with striking yellow crest feathers"}, 
{"The Eurasian Spoonbill is a wading bird with a distinctive spoon-shaped bill"}, 
{"The Blue Tit is a small bird with blue and yellow plumage and is found in Europe and Asia"}, 
{"The Common Ringed Plover is a shorebird with a distinctive black ring around its neck"}, 
{"The Eurasian Coot is a water bird known for its distinctive white frontal shield"}, 
{"The Blue-black Grassquit is a small finch with blue-black plumage, found in the Americas"}, 
{"The White-throated Magpie-Jay is known for its striking blue and white plumage"}, 
{"The Common Grackle is a songbird with iridescent plumage and is found in North America"}, 
{"The Rufous Treecreeper is a small bird that climbs tree trunks in search of insects"}, 
{"The Indian Robin is a bird with black and white plumage and is found in South Asia"}, 
{"The Green Hermit is a hummingbird with vibrant green plumage and a long, straight bill"}, 
{"The White-cheeked Starling is a bird with a distinctive white cheek patch"}, 
{"The Crested Lark is a songbird with a distinctive crest on its head, found in Europe and Asia"}, 
{"The Superb Fairywren is a small bird with striking blue and black plumage, native to Australia"}
};